<?php

return [
    'take_movie' => 12,
    'pagination_movie' => 8,
    'default_prioritize' => 1,
    'default_server' => 1,
    'default_nomination' => 1,
    'genre_of_movie' => 1,
    'genre_of_tvserie' => 2,
    'status_true' => 1,
    'default_order' => 1,
    'default_id_genre_movie' => 0,
    'default_id_genre_tvserie' => 1,
    'default_chap' => 1,
    'default_name_genre' => 'genre',
    'default_name_country' => 'country',
    'contact_email' => 'minhquang31011998@gmail.com',
    'contact_phone' => '+84368695921',
    'scr_ytb_default' => 'https://www.youtube.com/embed/',
    'user_created_by' => 'Minh Quang',
    'nomination_off' => 0,
    'nomination_on' => 1,
    'store_images_movie' => 'public/images',
    'link_images_movie' => '/storage/images/',
    'image_store' => '/images/',
    'status_active' => 1,
    'status_hidden' => 0,
    'default_channel' => 1,
    'role_admin' => 1,
    'role_user' => 2,
    'take_user' => 6,
    'number_after_float' => 1,
    'contact_name' => 'Admin-Film',
    'admin_email' => 'minhquang31011998@gmail.com',
    'random_password' => 8,
    'day_send_mail' => 30,
    'time_send_mail' => '20:00',
];
