<?php

return [
    'take_movie' => 12,
    'pagination_movie' => 8,
    'default_prioritize' => 1,
    'default_server' => 1,
    'default_nomination' => 1,
    'genre_of_movie' => 1,
    'genre_of_tvserie' => 2,
    'status_true' => 1,
    'default_order' => 1,
    'default_id_genre_movie' => 0,
    'default_id_genre_tvserie' => 1,
    'default_chap' => 1,
    'default_name_genre' => 'genre',
    'default_name_country' => 'country',
    'contact_email' => 'minhquang31011998@gmail.com',
    'contact_phone' => '+84368695921',
    'scr_ytb_default' => 'https://www.youtube.com/embed/',
    'user_created_by' => 'Minh Quang',
    'icon_favicon'  => 'bower_components/bower_film/backend/icon/favicon-32x32.png',
    'logo'  => 'bower_components/bower_film/backend/img/logo.svg',
    'logo_png' => 'bower_components/bower_film/img/LOGO.png',
];
